# Import Libraries

In [3]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
%matplotlib inline


# Define XOR Data Set

In [13]:
X = np.array([
    [1,1,1],
    [1,0,1],
    [0,1,1],
    [0,0,1],
])

y = np.array([[0],
            [1],
            [1],
            [0]])


In [14]:
X

array([[1, 1, 1],
       [1, 0, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [5]:
y

array([[0],
       [1],
       [1],
       [0]])

# Define Parameters


In [6]:
# Learning Rate
eta = 3

# Number of epochs for learning
epochs = 300

# Number of Hidden Neurons
hidden = 5

# Set Weights

In [7]:
w01 = np.random.random((len(x[0]), hidden))
w12 = np.random.random((hidden, 1))

In [9]:
w01

array([[ 0.05396807,  0.80256303,  0.09546641,  0.55780349,  0.12341064],
       [ 0.99685084,  0.40196741,  0.4144717 ,  0.27624103,  0.50951673],
       [ 0.03074355,  0.07997243,  0.70740782,  0.37470689,  0.60605188]])

In [10]:
w12

array([[ 0.7440396 ],
       [ 0.08188494],
       [ 0.4889105 ],
       [ 0.79553683],
       [ 0.83445508]])

# Define Functions

In [22]:
def sigmoid(x, derivative=False):
    if derivative:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

def feedforward(X):
    z_h = np.dot(X, w01)
    a_h = sigmoid(z_h)

    z_o = np.dot(a_h, w12)
    a_o = sigmoid(z_o)
    return(a_o,a_h)


# Train the Algorithim- Feed Forward

In [44]:
a_o, a_h = feedforward(X)

In [45]:
a_o

array([[ 0.4491188 ],
       [ 0.44790774],
       [ 0.46595111],
       [ 0.46720834]])

In [46]:
a_h

array([[ 0.69324143,  0.77855301,  0.74205305,  0.718788  ,  0.72395899],
       [ 0.46882098,  0.70278041,  0.66301487,  0.67190227,  0.62546817],
       [ 0.69231235,  0.61294599,  0.72955625,  0.60645478,  0.70945843],
       [ 0.46773408,  0.51575278,  0.64850271,  0.55250025,  0.60859104]])

In [29]:
a_o_error = ((1 / 2) * (np.power((a_o - y), 2)))

In [30]:
a_o_error

array([[ 0.40971526],
       [ 0.00821451],
       [ 0.00575583],
       [ 0.36389358]])

In [32]:
sum(a_o_error)

array([ 0.78757917])

# Back propogation

In [33]:
delta_a_o_error = a_o - y
delta_z_o = sigmoid(a_o,derivative=True)
delta_w12 = a_h
delta_output_layer = np.dot(delta_w12.T,(delta_a_o_error * delta_z_o))


In [34]:
delta_output_layer

array([[ 0.09724049],
       [ 0.09993248],
       [ 0.11389099],
       [ 0.10612761],
       [ 0.11198886]])

# Hidden to Imput layer weights

In [36]:
delta_a_h = np.dot(delta_a_o_error * delta_z_o, w12.T)
delta_z_h = sigmoid(a_h,derivative=True)
delta_w01 = X
delta_hidden_layer = np.dot(delta_w01.T, delta_a_h * delta_z_h)

In [37]:
delta_hidden_layer

array([[ 0.00826715,  0.00083696,  0.00519533,  0.00863001,  0.00866343],
       [ 0.00944258,  0.00088114,  0.00576058,  0.00909746,  0.00969251],
       [ 0.02666447,  0.00282341,  0.01582394,  0.02732149,  0.02744305]])

# Update the weights

In [52]:
w01 = w01 - eta * delta_hidden_layer
w12 = w12 - eta * delta_output_layer

In [53]:
w01

array([[-0.02043626,  0.79503036,  0.04870845,  0.48013343,  0.0454398 ],
       [ 0.91186765,  0.39403717,  0.36262646,  0.19436388,  0.42228414],
       [-0.2092367 ,  0.05456178,  0.56499233,  0.12881345,  0.35906439]])

In [54]:
w12

array([[-0.13112479],
       [-0.81750737],
       [-0.53610842],
       [-0.15961163],
       [-0.17344463]])

# Sample Learned Output

In [7]:
a_o, a_h = feedforward(X)
print(a_o)

NameError: name 'feedforward' is not defined

# Plot Learning Curves

In [10]:
def plot_leaning_curve(estimator, title, X, y, ylim=None, cv= None,
                      n_jobs=None, train_sizes=np.linspace(.1, 1.0, 5)):
    plt.figure()
    plt.title(title)
    if ylim is not None:
        plt.ylim(*ylim)
        plt.xlabel("Training examples")
        plt.ylabel("Score")
        train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes)
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    plt.grid()
    
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                    train_scores_mean + train_scores_std, alpha=0.1,
                     color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                    test_scores_mean + test_scores_std, alpha=0.1, color="g")
    plt.plot(train_sizes, train_scores_mean, '0-', color="r",label="Training score")
    plt.plot(train_sizes, test_scores_mean, '0-', color="g",
            label="Cross-validation score")
    
    plt.legend(loc="best")
    return plt

digits = load_digits()
X, y = digits.data, digits.target

title = "Learning Curves (Naive Bayes)"
cv= ShuffleSplit(n_splits=100, test_Size=0.2, random_state=0)

estimator = GaussianNB()
plot_learning_curves(estimator, title, X, y, ylim=(0.7, 1.01), cv=cv, n_jobs=4)

title = "Learning Curves (SVM, RBF Kernel, $\gamma=0.001$)"
cv = ShuffleSplit(n_splits=10,test_size=0.2, random_state=0)
estimator = SVC(gamma=0.001)
plot_learning_curves(estimator, title, X, y, (0.7,1.01), cv=cv, n_jobs=4)
plt.show

TypeError: __init__() got an unexpected keyword argument 'test_Size'